
#' Forest plot individual gene from 2x3 factor analysis
#' 
#' @param object A 'volc3d' class object from a 2x3 analysis generated by
#'   [deseq_2x3_polar()]
#' @param gene Gene to plot
#' @param scheme Vector of 3 colours for plotting
#' @param labs Optional character vector of labels for the groups
#' @param error_type Either "ci" or "se" to specify whether error bars use 95%
#'   confidence intervals or standard error.
#' @param transpose Logical whether to transpose the plot
#' @param ... Optional arguments passed to [plot()]
#' @seealso [deseq_2x3_polar()]
#' @importFrom graphics abline arrows axis par points text
#' @export

forest_plot <- function(object, gene,
                        scheme = c('red', 'green3', 'blue'),
                        labs = NULL,
                        error_type = c("ci", "se"),
                        transpose = FALSE,
                        ...) {
  if (!is(object, "volc3d") | length(obj@df) != 3) {
    stop("Not a 2x3 analysis 'volc3d' class object")}
  error_type <- match.arg(error_type)
  df <- object@df[[2]]
  x <- unlist(df[gene, 1:3])
  xCI <- unlist(df[gene, 4:6])
  if (error_type == "ci") xCI <- xCI * 1.96
  xrange <- range(c(x-xCI, x+xCI, 0), na.rm=TRUE)
  if (transpose) {
    op <- par(mar=c(5, 7, 2, 4))
    on.exit(par(op))
    new.args <- list(...)
    plot.args <- list(x = NA, ylim = xrange, xlim = c(1,3), xaxt="n", bty = "n",
                      ylab = bquote(.(gene) ~"log"[2]~"FC"), xlab = "", las = 1)
    if (length(new.args)) plot.args[names(new.args)] <- new.args
    do.call("plot", plot.args)
    arrows(1:3, x-xCI, y1 = x+xCI, code=3, angle=90, length=0.05,
           col=scheme)
    points(1:3, x, pch=19, col=scheme)
    abline(h = 0, lty = 2)
    if (is.null(labs)) labs <- colnames(df)[1:3]
    axis(1, 1:3, labs, tick = FALSE, las = 1)
    stars <- stars.pval(object@padj[gene,])
    text(1:3, xrange[2]+ diff(xrange)*0.06, stars, xpd = NA)
  } else {
    op <- par(mar=c(5, 7, 2, 4))
    on.exit(par(op))
    new.args <- list(...)
    plot.args <- list(x = NA, xlim = xrange, ylim = c(1,3), yaxt="n", bty = "n",
                      xlab = bquote(.(gene) ~"log"[2]~"FC"), ylab = "")
    if (length(new.args)) plot.args[names(new.args)] <- new.args
    do.call("plot", plot.args)
    arrows(x-xCI, 3:1, x+xCI, code=3, angle=90, length=0.05,
           col=scheme)
    points(x, y = 3:1, pch=19, col=scheme)
    abline(v = 0, lty = 2)
    if (is.null(labs)) labs <- colnames(df)[1:3]
    axis(2, 3:1, labs, tick = FALSE, las = 1)
    stars <- stars.pval(object@padj[gene,])
    text(xrange[2]+ diff(xrange)*0.06, 3:1, stars, xpd = NA)
  }
}

#' Forest plot individual gene from 2x3 factor analysis using plotly
#' 
#' @param object A 'volc3d' class object from a 2x3 analysis generated by
#'   [deseq_2x3_polar()]
#' @param gene Gene to plot
#' @param scheme Vector of 3 colours for plotting
#' @param labs Optional character vector of labels for the groups
#' @param error_type Either "ci" or "se" to specify whether error bars use 95%
#'   confidence intervals or standard error.
#' @param transpose Logical whether to transpose the plot
#' @seealso [deseq_2x3_polar()]
#' @export
forest_plotly <- function(object, gene,
                          scheme = c('red', 'green3', 'blue'),
                          labs = NULL,
                          error_type = c("ci", "se"),
                          transpose = FALSE) {
  if (!is(object, "volc3d") | length(obj@df) != 3) {
    stop("Not a 2x3 analysis 'volc3d' class object")}
  error_type <- match.arg(error_type)
  df <- object@df[[2]]
  x <- unlist(df[gene, 1:3])
  xCI <- unlist(df[gene, 4:6])
  if (error_type == "ci") xCI <- xCI * 1.96
  xrange <- range(c(x-xCI, x+xCI, 0), na.rm=TRUE)
  if (is.null(labs)) labs <- colnames(df)[1:3]
  labs <- factor(labs, levels = labs)
  data <- data.frame(x, xCI, labs)
  stars <- stars.pval(object@padj[gene,])
  if (!transpose) {
    annot <- list(y = data$labs, x = max(x+xCI, na.rm = TRUE), text = stars,
                  showarrow = FALSE, xanchor='left')
    plot_ly(data = data, x = ~x, y = ~labs,
            colors = scheme, color = ~labs,
            type = 'scatter', mode = 'markers',
            error_x = list(array = ~xCI, color = ~labs)) %>%
      layout(xaxis = list(title = paste(gene, "log<sub>2</sub> FC")),
             yaxis = list(title = ""),
             annotations = annot)
  } else {
    annot <- list(x = data$labs, y = max(x+xCI, na.rm = TRUE), text = stars,
                  showarrow = FALSE, yanchor='bottom')
    plot_ly(data = data, y = ~x, x = ~labs,
            colors = scheme, color = ~labs,
            type = 'scatter', mode = 'markers',
            error_y = list(array = ~xCI, color = ~labs)) %>%
      layout(yaxis = list(title = paste(gene, "log<sub>2</sub> FC")),
             xaxis = list(title = ""),
             annotations = annot)
  }
}


# code modified from orphaned package gtools

#' @importFrom stats symnum
stars.pval <- function(p.value) {
  unclass(
    symnum(p.value,
           corr = FALSE, na = FALSE,
           cutpoints = c(0, 0.001, 0.01, 0.05, 1),
           symbols = c("***", "**", "*", " ")
    )
  )
}
